create table user(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) not null,
    email varchar(100) not null UNIQUE,
    password varchar(100) not null,
    type varchar(50) DEFAULT 'ROLE_USER'
)